import { Jura } from "next/font/google"; // ✅ Import Jura font
import "./globals.css";
import TopNavBar from "@/app/components/TopNavBar";
import MainNavbar from "@/app/components/MainNavbar";
import FooterInfo from "@/app/components/FooterInfo";
import FooterContactInfo from "@/app/components/FooterContactInfo";
import Footer from "@/app/components/Footer";
import ReduxProvider from "../../providers/reduxProvider";
import { Toaster } from "react-hot-toast";

// Configure Jura font
const jura = Jura({
  subsets: ["latin"],
  variable: "--font-jura",
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Heaven Holiday",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Toaster position="top-right" />
      <ReduxProvider>
        <body className={`${jura.variable} antialiased`}>
          <TopNavBar />
          <MainNavbar />
          {children}

          <FooterInfo />
          <FooterContactInfo />
          <Footer />
        </body>
      </ReduxProvider>
    </html>
  );
}
